# PANDAS ASSIGNMENT
# Pandas for AI/ML – Conceptual & Technical Assignment


**Name:** Kala Sravani  
**Batch:** 2

In [1]:
import numpy as np
import pandas as pd

#  Output Prediction
Predict the exact output of the given code snippets. Explain the underlying Pandas operation wherever required.


### Q1. Array Operations and Vectorization

In [ ]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

### 1.Predict the output of both statements.

**Output:**

For NumPy array:
[20 40 60]

For Pandas Series:

0     20

1     40

2     60

dtype: int64
### 2.Identify one similarity and one difference between the two data structures.


**Similarity:** Both NumPy arrays and Pandas Series support vectorized operations, so multiplying by 2 multiplies every element by 2.

**Difference:** A NumPy array displays only the values, whereas a Pandas Series displays the values along with their index.

**Explanation:** The `* 2` operation is applied element-wise to all values in both data structures.

### Q2. Boolean Filtering


In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

### 1.Predict the rows displayed.

**Rows displayed:**

 Student | Marks
 
 B       | 80    
 C       | 65    
 D       | 90   

### 2.How many rows and columns will the resulting DataFrame contain?

**Number of rows:** 3

**Number of columns:** 2

**Explanation:** The condition `df['Marks'] >= 65` filters the DataFrame and keeps only the students whose marks are 65 or above.

### Q3. Descriptive Statistics

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())


### 1.Predict all three outputs.

**Mean:** 30.0

**Maximum:** 50

**Median:** 30.0

### 2.Explain how the median differs from the mean.

**Difference between Mean and Median:**  
Mean is calculated by adding all the values and dividing by the number of values. Median is the middle value when the data is arranged in ascending or descending order.

**Explanation:** The `mean()` calculates the average, `max()` returns the highest value, and `median()` returns the middle value of the Marks column.

### Q4. Group-wise Analysis

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())

### 1.Predict the output.
**Output:**

HR    40000.0  
IT    50000.0
### 2.Explain how groupby() calculates the department-wise average.

**Explanation:** `groupby('Department')` groups the employees according to their department. Then `['Salary'].mean()` calculates the average salary separately for each department.

**Calculation:**
- HR = (30000 + 50000) / 2 = 40000
- IT = (40000 + 60000) / 2 = 50000

### Q5. Pandas Correlation - Positive

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


### 1.Predict the correlation coefficient.

**Correlation coefficient:** 1.0
### 2.Interpret the direction and strength of the relationship

**Interpretation:** The correlation is positive and perfect. This means that as study hours increase, marks also increase in a perfectly linear relationship.

**Explanation:** The `corr()` function calculates the correlation between the Hours and Marks columns. A value of `1.0` indicates a perfect positive correlation.

### Q6. Pandas Correlation - Negative

In [5]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

-1.0


### 1.Predict the correlation coefficient.

**Correlation coefficient:** -1.0

### 2.Explain what the sign of the coefficient indicates about the relationship.

**Interpretation:** The correlation is negative and perfect. This means that as Price increases, Demand decreases in a perfectly linear relationship.

**Explanation:** The `corr()` function calculates the correlation between the Price and Demand columns. A value of `-1.0` indicates a perfect negative correlation.

# Section B – Code Correction

### Q1. JSON and CSV

In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")
print(df)


### 1.A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.

**Correction:** Remove `header=None` from `pd.read_csv()`.

**Correct code:**
`df = pd.read_csv("students.csv")`

**Explanation:** By default, `pd.read_csv()` treats the first row of the CSV file as the column headers. Using `header=None` tells Pandas that there is no header row, which would cause the first row of the file to be treated as data instead.

### Q2. Data Analysis

In [8]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


### 1.The objective is to display the five highest salaries from a DataFrame. Correct the code.

**Correction:** Add `ascending=False` to `sort_values()`.

**Correct code:**
`df.sort_values('Salary', ascending=False).head(5)`

**Explanation:** By default, `sort_values()` sorts in ascending order. Setting `ascending=False` sorts the salaries from highest to lowest, and `head(5)` selects the first five records.

### Q3. Cleaning Data

In [9]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


### 1.A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code

**Correction:** Assign the result of `fillna()` back to the `Marks` column.

**Correct code:**
`df['Marks'] = df['Marks'].fillna(df['Marks'].mean())`

**Explanation:** `fillna()` returns a new Series by default. Assigning it back to `df['Marks']` updates the DataFrame by replacing the missing value with the column mean.

### Q4. Correlation

In [10]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df[['Hours', 'Marks']].corr().loc['Hours', 'Marks'])

1.0


### 1.The objective is to calculate the correlation between Hours and Marks. Correct the code.

**Correction:** Select the `Hours` and `Marks` columns first, calculate their correlation matrix, and then access the correlation between the two columns.

**Correct code:**
`df[['Hours', 'Marks']].corr().loc['Hours', 'Marks']`

**Explanation:** The `corr()` function calculates the correlation matrix for the selected columns. `.loc['Hours', 'Marks']` retrieves the correlation coefficient between Hours and Marks.

# Section C – Edge Cases

### Q1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?



In [11]:
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


### 1.Identify the shapes of arrays a and b before addition.

**Shape of `a`:** (3, 1)

**Shape of `b`:** (1, 3)

### 2.Predict the output of the given code

**Output:**

[[11 12 13]

 [21 22 23]
 
 [31 32 33]]

**Result shape:** (3, 3)
### 3.Explain how NumPy broadcasting enables the addition of these arrays.

**Explanation:** NumPy broadcasting expands the dimensions of the two arrays so that the shapes are compatible. The values in `b` are effectively repeated across the rows, while the values in `a` are repeated across the columns.
### 4.What would happen if b were replaced with np.array([1, 2])? Explain the reason.

**If `b` is replaced with `np.array([1, 2])`:**  
The addition will raise a broadcasting error because the dimensions `(3, 1)` and `(2,)` are not compatible for element-wise addition.

### Q2.A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.


In [12]:
import pandas as pd
from io import StringIO

data = """ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA"""

df = pd.read_csv(StringIO(data))

print(df)
print(df.dtypes)

    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN
ID         int64
Name         str
Date         str
Marks    float64
dtype: object


In [13]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')

print(df)
print(df.dtypes)

    ID     Name       Date  Marks
0  101  Asha, R 2026-01-09   80.0
1  102     Ravi        NaT    NaN
2  103     Neha 2026-03-09    NaN
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object


### 1.Predict how the quoted comma in "Asha, R" will be handled when the CSV file is read.

**Quoted comma:** The comma inside `"Asha, R"` is treated as part of the Name field because the value is enclosed in quotes.
### 2.Identify the potential issues with the Date and Marks columns.

**Date issue:** The Date column contains different date formats, so it should be converted to a consistent datetime format.
### 3.Rewrite the code to handle missing marks and convert the date column into a suitable date-time format.

**Marks issue:** Blank values and `NA` can be interpreted as missing values. `pd.to_numeric(..., errors='coerce')` converts invalid or missing values to `NaN`.
### 4.Explain why the value "NA" should be investigated before deciding whether it represents a missing value.

**Why investigate `NA`?** The value `NA` should be investigated before treating it as missing because it may represent a specific status or category rather than an actually missing value.

**Explanation:** Using `pd.to_datetime()` standardizes the Date column, while `pd.to_numeric()` converts the Marks column into a numeric type and safely handles invalid values.

### Q3.. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0


In [15]:
highest_salary = df.loc[df["Salary"].idxmax()]

print(highest_salary)

Employee           D
Salary      10000000
Name: 3, dtype: object


### 1.Predict the mean and median salary.

**Mean salary:** 2,522,500.0

**Median salary:** 32,500.0
### 2.Identify the effect of the extreme salary on the mean.

**Effect of the extreme value:** The salary of 10,000,000 is much larger than the other salaries, so it increases the mean significantly. The median is much less affected by the extreme value.
### 3.Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.

**Statistic that better represents a typical salary:** The median may better represent a typical employee's salary in this dataset because it is less affected by the extreme value.
### 4.Write code to identify the employee record with the highest salary and explain why the record should be investigated before removing it

**Highest salary record:** Employee D with a salary of 10,000,000.

**Why investigate the record:** The unusually high salary should be investigated to determine whether it is a genuine value or a data-entry/error issue before deciding whether to remove it.

# Section D – Scenario-Based Problems

### Q1.A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing

In [17]:
import pandas as pd

df = pd.DataFrame({
    'Student_ID': ['S101', 'S102', 'S103', 'S104', 'S105', 'S106',
                   'S107', 'S108', 'S102', 'S109', 'S110', 'S111',
                   'S112', 'S113', 'S114'],
    'Student_Name': ['Asha', 'Ravi', 'Neha', 'Karan', 'Meera', 'Arjun',
                     'Priya', 'Rahul', 'Ravi', 'Sneha', 'Varun', 'Diya',
                     'Aman', 'Nisha', 'Kabir'],
    'Department': ['IT', 'it', 'I.T.', 'HR', 'HR', 'Finance',
                   'finance', 'IT', 'it', 'I.T.', 'HR', 'Finance',
                   'IT', 'HR', 'Finance'],
    'Assessment': ['Python'] * 15,
    'Marks': [85, 78, 92, None, 'Absent', 0, 67, 75, 78,
              'NA', '88 marks', 91, None, 64, 105]
})

print(df)

   Student_ID Student_Name Department Assessment     Marks
0        S101         Asha         IT     Python        85
1        S102         Ravi         it     Python        78
2        S103         Neha       I.T.     Python        92
3        S104        Karan         HR     Python      None
4        S105        Meera         HR     Python    Absent
5        S106        Arjun    Finance     Python         0
6        S107        Priya    finance     Python        67
7        S108        Rahul         IT     Python        75
8        S102         Ravi         it     Python        78
9        S109        Sneha       I.T.     Python        NA
10       S110        Varun         HR     Python  88 marks
11       S111         Diya    Finance     Python        91
12       S112         Aman         IT     Python      None
13       S113        Nisha         HR     Python        64
14       S114        Kabir    Finance     Python       105


## Using Pandas, perform the following cleaning operations in sequence:

### 1.Load the CSV file and inspect the dataset using head(), info(), and isnull().sum().


In [18]:
print(df.head())
print(df.info())
print(df.isnull().sum())

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python    None
4       S105        Meera         HR     Python  Absent
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Student_ID    15 non-null     str   
 1   Student_Name  15 non-null     str   
 2   Department    15 non-null     str   
 3   Assessment    15 non-null     str   
 4   Marks         13 non-null     object
dtypes: object(1), str(4)
memory usage: 732.0+ bytes
None
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           2
dtype: int64


### 2.Standardize department names so that IT, it, and I.T. are represented consistently. Apply the same approach to Finance.

In [28]:
df['Department'] = df['Department'].replace({
    'it': 'IT',
    'I.T.': 'IT',
    'finance': 'Finance'
})

print(df['Department'])

0          IT
1          IT
2          IT
3          HR
4          HR
5     Finance
6     Finance
7          IT
8          IT
9          IT
10         HR
11    Finance
12         IT
13         HR
14    Finance
Name: Department, dtype: str


**Explanation:** The `replace()` method standardizes inconsistent department names so that `IT`, `it`, and `I.T.` become `IT`, while `Finance` and `finance` become `Finance`.

duplicates = df[df.duplicated(keep=False)]

print(duplicates)

df = df.drop_duplicates()

print(df)

**Explanation:** `duplicated()` identifies repeated records, while `drop_duplicates()` removes exact duplicate rows and keeps the first occurrence by default.

### 3.Identify and remove exact duplicate student assessment records.


In [20]:
df['Marks'] = df['Marks'].replace({
    'Absent': pd.NA,
    'NA': pd.NA
})

df['Marks'] = (
    df['Marks']
    .astype('string')
    .str.extract(r'(\d+(?:\.\d+)?)', expand=False)
)

df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')

print(df[['Student_ID', 'Student_Name', 'Marks']])

   Student_ID Student_Name  Marks
0        S101         Asha     85
1        S102         Ravi     78
2        S103         Neha     92
3        S104        Karan   <NA>
4        S105        Meera   <NA>
5        S106        Arjun      0
6        S107        Priya     67
7        S108        Rahul     75
8        S102         Ravi     78
9        S109        Sneha   <NA>
10       S110        Varun     88
11       S111         Diya     91
12       S112         Aman   <NA>
13       S113        Nisha     64
14       S114        Kabir    105


**Explanation:** The `replace()` method treats `Absent` and `NA` as missing values. The regular expression extracts numeric values from entries such as `88 marks`, and `pd.to_numeric()` converts the cleaned values into a numeric format. Invalid or missing values become `NaN`.

### 4.Convert the Marks column into a numeric format, handling "88 marks", "Absent", "NA", and blank entries appropriately.

In [21]:
df['Marks_Status'] = df['Student_ID'].map({
    'S104': 'Not Entered',
    'S105': 'Absent',
    'S109': 'Needs Investigation',
    'S112': 'Not Entered'
}).fillna('Recorded')

print(df[['Student_ID', 'Student_Name', 'Marks', 'Marks_Status']])

   Student_ID Student_Name  Marks         Marks_Status
0        S101         Asha     85             Recorded
1        S102         Ravi     78             Recorded
2        S103         Neha     92             Recorded
3        S104        Karan   <NA>          Not Entered
4        S105        Meera   <NA>               Absent
5        S106        Arjun      0             Recorded
6        S107        Priya     67             Recorded
7        S108        Rahul     75             Recorded
8        S102         Ravi     78             Recorded
9        S109        Sneha   <NA>  Needs Investigation
10       S110        Varun     88             Recorded
11       S111         Diya     91             Recorded
12       S112         Aman   <NA>          Not Entered
13       S113        Nisha     64             Recorded
14       S114        Kabir    105             Recorded


### 5.Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.


In [22]:
invalid_mask = df['Marks'].notna() & ~df['Marks'].between(0, 100)

invalid_marks = df.loc[invalid_mask]

print(invalid_marks[['Student_ID', 'Student_Name', 'Marks']])

   Student_ID Student_Name  Marks
14       S114        Kabir    105


**Explanation:**  Marks outside the valid 0–100 range are treated as invalid and should be investigated before including them in analysis.

### 6.Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.


In [23]:
invalid_mask = df['Marks'].notna() & ~df['Marks'].between(0, 100)

df.loc[invalid_mask, 'Marks'] = pd.NA

print(df[['Student_ID', 'Student_Name', 'Marks']])

   Student_ID Student_Name  Marks
0        S101         Asha     85
1        S102         Ravi     78
2        S103         Neha     92
3        S104        Karan   <NA>
4        S105        Meera   <NA>
5        S106        Arjun      0
6        S107        Priya     67
7        S108        Rahul     75
8        S102         Ravi     78
9        S109        Sneha   <NA>
10       S110        Varun     88
11       S111         Diya     91
12       S112         Aman   <NA>
13       S113        Nisha     64
14       S114        Kabir   <NA>


In [24]:
print(df.isnull().sum())

Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           5
Marks_Status    0
dtype: int64


In [25]:
print(df)

   Student_ID Student_Name Department Assessment  Marks         Marks_Status
0        S101         Asha         IT     Python     85             Recorded
1        S102         Ravi         IT     Python     78             Recorded
2        S103         Neha         IT     Python     92             Recorded
3        S104        Karan         HR     Python   <NA>          Not Entered
4        S105        Meera         HR     Python   <NA>               Absent
5        S106        Arjun    Finance     Python      0             Recorded
6        S107        Priya    Finance     Python     67             Recorded
7        S108        Rahul         IT     Python     75             Recorded
8        S102         Ravi         IT     Python     78             Recorded
9        S109        Sneha         IT     Python   <NA>  Needs Investigation
10       S110        Varun         HR     Python     88             Recorded
11       S111         Diya    Finance     Python     91             Recorded

### 6.Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified.



In [26]:
records_removed = 1
missing_marks_remaining = df['Marks'].isna().sum()
invalid_marks_identified = 1

print("Records removed:", records_removed)
print("Missing marks remaining:", missing_marks_remaining)
print("Invalid marks identified:", invalid_marks_identified)

Records removed: 1
Missing marks remaining: 5
Invalid marks identified: 1
